PORTNAME=	serialport
PORTVERSION=	${QT5_VERSION}${QT5_KDE_PATCH}
PORTREVISION=	1
CATEGORIES=	comms
PKGNAMEPREFIX=	qt5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Qt functions to access serial ports

USES=		compiler:c++11-lang libtool qmake qt-dist:5,serialport
USE_QT=		core buildtools_build

.include <bsd.port.mk>
