PORTNAME=	aura-browser
DISTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=	www kde kde-plasma

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Plasma5 browser for bigscreen
WWW=		https://www.kde.org/plasma-desktop

USES=		cmake kde:5 qt:5 tar:xz
USE_KDE=	ecm i18n kirigami2
USE_QT=		core declarative multimedia webengine widgets \
		buildtools:build qmake:build

.include <bsd.port.mk>
