PORTNAME=	websockets
PORTVERSION=	${QT5_VERSION}${QT5_KDE_PATCH}
PORTREVISION=	1
CATEGORIES=	www
PKGNAMEPREFIX=	qt5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Qt implementation of WebSocket protocol

USES=		compiler:c++11-lang qmake:norecursive qt-dist:5,websockets
USE_QT=		buildtools_build core network

.include <bsd.port.mk>
