PORTNAME=	oxygen-sounds
DISTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=	x11-themes kde kde-plasma

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Plasma5 Oxygen style

LICENSE=	GPLv2 LGPL21
LICENSE_COMB=	multi

USES=		cmake kde:5 pkgconfig qt:5 tar:xz
USE_KDE=	ecm
USE_QT=		buildtools_build qmake_build

.include <bsd.port.mk>
